In [18]:
import numpy as np

In [19]:
lista = [1,2]
lista

[1, 2]

In [20]:
lista * 2

[1, 2, 1, 2]

In [21]:
arr = np.arange(0,10)
arr2 = arr.copy()
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

operaciones

In [22]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr * 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [28]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [29]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
1 / arr

/tmp/ipykernel_17565/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [31]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
arr / arr2

/tmp/ipykernel_17565/1444868932.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [35]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [37]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [38]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [39]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])