In [1]:
import pandas as pd
import numpy as np

In [2]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
arr = np.array(lista, dtype='float64')
arr

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [12]:
type(arr)

numpy.ndarray

In [5]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr[0] - matriz[0]

array([ 0, -1, -2])

In [7]:
arr[1] + matriz[0,2]

5

In [8]:
arr[0:3] - matriz[0:2]

array([[ 0,  0,  0],
       [-3, -3, -3]])

In [9]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])