In [2]:
import numpy as np

In [3]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [4]:
vector = np.array([1,5,9])
print(vector)
vector.ndim

[1 5 9]


1

In [5]:
matriz = np.array([[1,5,9],[9,8,7]])
print(matriz)
matriz.ndim

[[1 5 9]
 [9 8 7]]


2

In [6]:
tensor = np.array([[[1,5,9],[9,8,7],[1,2,3]],[[1,5,9],[9,8,7],[1,2,3]]])
print(tensor)
tensor.ndim

[[[1 5 9]
  [9 8 7]
  [1 2 3]]

 [[1 5 9]
  [9 8 7]
  [1 2 3]]]


3

Agregar o eliminar dimensiones

In [7]:
vector = np.array([1,5,9], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 5 9]]]]]]]]]]


10

In [8]:
expand = np.expand_dims(np.array([1,5,9]), axis=0)
print(expand)
expand.ndim

[[1 5 9]]


2

In [9]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 5 9]]]]]]]]]] 10
[1 5 9] 1


In [10]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [13]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
np.linspace(3,10,20)

array([ 3.        ,  3.36842105,  3.73684211,  4.10526316,  4.47368421,
        4.84210526,  5.21052632,  5.57894737,  5.94736842,  6.31578947,
        6.68421053,  7.05263158,  7.42105263,  7.78947368,  8.15789474,
        8.52631579,  8.89473684,  9.26315789,  9.63157895, 10.        ])

In [22]:
np.eye(2,4,1,dtype='int8')

array([[0, 1, 0, 0],
       [0, 0, 1, 0]], dtype=int8)

In [25]:
val_rand = np.random.rand(2,3)
print(val_rand)
val_rand.dtype

[[0.49458965 0.84823818 0.8928646 ]
 [0.92198323 0.44301847 0.94298006]]


dtype('float64')

In [26]:
val = np.random.randint(4,9,(2,8))
print(val)
val.dtype

[[6 7 5 5 8 5 8 6]
 [5 4 6 8 5 7 4 6]]


dtype('int64')