In [1]:
import numpy as np

In [2]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [3]:
vector = np.array([1,5,9])
print(vector)
vector.ndim

[1 5 9]


1

In [4]:
matriz = np.array([[1,5,9],[9,8,7]])
print(matriz)
matriz.ndim

[[1 5 9]
 [9 8 7]]


2

In [5]:
tensor = np.array([[[1,5,9],[9,8,7],[1,2,3]],[[1,5,9],[9,8,7],[1,2,3]]])
print(tensor)
tensor.ndim

[[[1 5 9]
  [9 8 7]
  [1 2 3]]

 [[1 5 9]
  [9 8 7]
  [1 2 3]]]


3

Agregar o eliminar dimensiones

In [6]:
vector = np.array([1,5,9], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 5 9]]]]]]]]]]


10

In [7]:
expand = np.expand_dims(np.array([1,5,9]), axis=0)
print(expand)
expand.ndim

[[1 5 9]]


2

In [8]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 5 9]]]]]]]]]] 10
[1 5 9] 1


In [9]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [41]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [42]:
np.linspace(3,10,20)

array([ 3.        ,  3.36842105,  3.73684211,  4.10526316,  4.47368421,
        4.84210526,  5.21052632,  5.57894737,  5.94736842,  6.31578947,
        6.68421053,  7.05263158,  7.42105263,  7.78947368,  8.15789474,
        8.52631579,  8.89473684,  9.26315789,  9.63157895, 10.        ])

In [57]:
np.eye(2,4,1,dtype='int')

array([[0, 1, 0, 0],
       [0, 0, 1, 0]])

In [75]:
val = np.random.randint(4,9,(3,4))
print(val)
val.dtype

[[5 7 7 6]
 [5 6 7 7]
 [8 5 5 4]]


dtype('int64')