In [23]:
import numpy as np

In [24]:
arr = np.random.randint(1,10,(3,4))
print(arr)
arr.shape

[[2 7 2 9]
 [5 9 7 8]
 [1 2 6 9]]


(3, 4)

In [37]:
np.reshape(arr,(2,2,-1),'C')

array([[[2, 7, 2],
        [9, 5, 9]],

       [[7, 8, 1],
        [2, 6, 9]]])