In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,4))
print(arr)
arr.shape

[[2 7 7 2]
 [9 4 3 6]
 [3 6 3 4]]


(3, 4)

In [9]:
np.reshape(arr,(3,2,-1),'C')

array([[[2, 7],
        [7, 2]],

       [[9, 4],
        [3, 6]],

       [[3, 6],
        [3, 4]]])