In [4]:
import numpy as np

In [5]:
arr = np.random.randint(1,20,10)
arr

array([10,  1,  5,  9, 15,  7,  8, 10, 11, 13])

In [6]:
matriz = arr.reshape(2,5)
matriz

array([[10,  1,  5,  9, 15],
       [ 7,  8, 10, 11, 13]])

In [7]:
arr.max()

15

In [11]:
matriz.max(1)

array([15, 13])

In [ ]:
matriz.max(0)

In [12]:
arr.argmax()

4

In [15]:
matriz.argmax(0)

array([0, 1, 1, 1, 0])

In [16]:
arr.min()

1

In [18]:
matriz.min(1)

array([1, 7])

In [22]:
matriz.argmin(1)

array([1, 0])

In [25]:
arr.argmin()

1

In [26]:
arr.ptp()

14

In [27]:
matriz.ptp(0)

array([3, 7, 5, 2, 2])

In [34]:
arr.sort()
arr

array([ 1,  5,  7,  8,  9, 10, 10, 11, 13, 15])

In [33]:
np.percentile(arr,50)

9.5

In [43]:
np.median(matriz,0)

array([ 5.5,  7.5,  9. , 10.5, 12. ])

In [49]:
np.std(matriz,1)

array([2.82842712, 1.93907194])

la varianza es la desviación estandar al cuadrado

In [53]:
np.std(arr) ** 2

14.29

In [51]:
np.var(arr)

14.289999999999997

In [54]:
np.mean(arr)

8.9

In [69]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [70]:
b = np.expand_dims(b,axis=0)
b

array([[5, 6]])

In [71]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [72]:
b.T

array([[5],
       [6]])

In [73]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [77]:
np.real(arr)

array([ 1,  5,  7,  8,  9, 10, 10, 11, 13, 15])