In [57]:
import numpy as np

In [58]:
arr = np.random.randint(1,20,10)
arr

array([ 3,  6,  5,  9,  7, 17, 16,  6, 16, 18])

In [59]:
matriz = arr.reshape(2,5)
matriz

array([[ 3,  6,  5,  9,  7],
       [17, 16,  6, 16, 18]])

In [60]:
arr.max()

18

In [61]:
matriz.max(1)

array([ 9, 18])

In [62]:
matriz.max(0)

array([17, 16,  6, 16, 18])

In [63]:
arr.argmax()

9

In [64]:
matriz.argmax(0)

array([1, 1, 1, 1, 1])

In [65]:
arr.min()

3

In [66]:
matriz.min(1)

array([3, 6])

In [67]:
matriz.argmin(1)

array([0, 2])

In [68]:
arr.argmin()

0

In [69]:
arr.ptp()

15

In [85]:
matriz.ptp(0)

array([ 6, 11, 10, 11, 11])

In [71]:
arr.sort()
arr

array([ 3,  5,  6,  6,  7,  9, 16, 16, 17, 18])

In [72]:
np.percentile(arr,50)

8.0

In [73]:
np.median(matriz,0)

array([ 6. , 10.5, 11. , 11.5, 12.5])

In [74]:
np.std(matriz,1)

array([1.356466  , 3.18747549])

la varianza es la desviación estandar al cuadrado

In [75]:
np.std(arr) ** 2

30.01

In [76]:
np.var(arr)

30.01

In [77]:
np.mean(arr)

10.3

In [78]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [79]:
b = np.expand_dims(b,axis=0)
b

array([[5, 6]])

In [80]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [81]:
b.T

array([[5],
       [6]])

In [82]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [83]:
np.real(arr)

array([ 3,  5,  6,  6,  7,  9, 16, 16, 17, 18])