In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [3]:
arr[(arr>5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [4]:
arr[arr>7]=99
arr

array([ 1,  2,  3,  4,  5,  6,  7, 99, 99, 99], dtype=int8)

In [5]:
arr[arr==99]

array([99, 99, 99], dtype=int8)